### ISSUE TITLE
ImportError: No module named _markerlib

### ISSUE THREAD

**Issue by ligi** [transifex/transifex-client#111]
on ubuntu 16.04 I get:
```

➜  ~ tx
Traceback (most recent call last):
  File "/usr/bin/tx", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 836, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2640, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2864, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2881, in _compute_dependencies
    from _markerlib import compile as compile_marker
ImportError: No module named _markerlib

```

**Comment by kouk** [comment]
@ligi can you give us some more information, such as the output of `pip freeze` and the version of the transifex client you are using?
Thanks

**Comment by ligi** [comment]
sure - pip freeze

```
adium-theme-ubuntu==0.3.4
attrs==15.2.0
beautifulsoup4==4.4.1
blinker==1.3
characteristic==14.3.0
chardet==2.3.0
cryptography==1.2.2
debtags==2.0
defer==1.0.6
dirspec==13.10
enum34==1.1.2
html5lib==0.999
httplib2==0.9.1
idna==2.0
ipaddress==1.0.16
lxml==3.5.0
markerlib==0.6.0
ndg-httpsclient==0.4.0
numpy==1.10.4
oauthlib==1.0.3
oneconf==0.3.9
PAM==0.4.2
Parsley==1.2
Pillow==3.1.1
piston-mini-client==0.7.5
psutil==3.4.2
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycups==1.9.73
pygobject==3.18.2
PyJWT==1.3.0
pyliblzma==0.5.3
pyOpenSSL==0.15.1
pyserial==3.0.1
python-apt==1.1.0b1
python-debian==0.1.27
pyxdg==0.25
service-identity==16.0.0
six==1.10.0
software-center-aptd-plugins==0.0.0
torbrowser-launcher==0.2.2
transifex-client==0.11
Twisted==16.0.0rc1
txsocksx==0.0.0
ubuntuone-client-data==14.4
unity-lens-photos==1.0
urllib3==1.14
wheel==0.29.0
zope.interface==4.1.3
```

transifex-client: 0.11.1+git15~g655c5e9-1

**Comment by kouk** [comment]
@ligi i'm not sure what to make of this. It seems that setuptools and markerlib aren't playing nice together on your system. We don't require markerlib by the way. I wonder if other applications that use setuptools work. You could try installing the transifex client in a virtualenv maybe? Or try uninstalling markerlib. Also, since Ubuntu 16.04 hasn't been released yet it might not have received enough testing.

**Comment by ligi** [comment]
tried uninstalling markerlib - did not help - might be a 16.04 thing but should be checked again when it gets released - pretty stable otherwise

**Comment by ligi** [comment]
It works again - closing

**Comment by galay-s** [comment]
> It works again - closing

How do you resolved it?

**Comment by mister-walter** [comment]
`pip install -U setuptools` fixed this issue for me in a Python 2.7 virtualenv on 16.04.

**Comment by hezhiy3** [comment]
I have met similar problem on Windows7 when I install distribute-0.7.3 for Python：

PS D:\桌面\Pythoner\各种tools\distribute-0.7.3>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to distribute.egg-info\requires.txt
writing distribute.egg-info\PKG-INFO
writing top-level names to distribute.egg-info\top_level.txt
writing dependency_links to distribute.egg-info\dependency_links.txt
reading manifest file 'distribute.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'distribute.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

creating build\bdist.win32\egg
creating build\bdist.win32\egg\EGG-INFO
copying distribute.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying distribute.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying distribute.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying distribute.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying distribute.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
copying distribute.egg-info\zip-safe -> build\bdist.win32\egg\EGG-INFO
creating 'dist\distribute-0.7.3-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing distribute-0.7.3-py2.7.egg
Removing c:\python27\lib\site-packages\distribute-0.7.3-py2.7.egg
Copying distribute-0.7.3-py2.7.egg to c:\python27\lib\site-packages
distribute 0.7.3 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\distribute-0.7.3-py2.7.egg
Processing dependencies for distribute==0.7.3
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    setuptools.setup(**setup_params)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\setuptools\command\install.py", line 73, in run
    self.do_egg_install()
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\setuptools\command\install.py", line 101, in do_egg_install
    cmd.run()
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\setuptools\command\easy_install.py", line 375, in run
    self.easy_install(spec, not self.no_deps)
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\setuptools\command\easy_install.py", line 599, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\setuptools\command\easy_install.py", line 650, in install_item
    self.process_distribution(spec, dist, deps)
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\setuptools\command\easy_install.py", line 701, in process_distributi
on
    [requirement], self.local_index, self.easy_install
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\pkg_resources.py", line 629, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\pkg_resources.py", line 2471, in requires
    dm = self._dep_map
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\pkg_resources.py", line 2682, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "D:\桌面\Pythoner\各种tools\distribute-0.7.3\pkg_resources.py", line 2699, in _compute_dependencies
    from _markerlib import compile as compile_marker
ImportError: No module named _markerlib

How can I fix this error?

**Comment by KingZuluKing** [comment]
same issue here persists on my system, 
`PS D:\Python_Programming_Zed_Show\Python27_Projects\simple_solver> pip install -U setuptools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future vers
st/development/release-process/#python-2-support
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 0.8b2
    Uninstalling setuptools-0.8b2:
      Successfully uninstalled setuptools-0.8b2
Successfully installed setuptools-41.2.0
PS D:\Python_Programming_Zed_Show\Python27_Projects\simple_solver>`

**Comment by KingZuluKing** [comment]
The same issue with markerlib persists on my system. Updated setuptools, and all the stuff but it does not work.

Curious if there are some solutions at the moment?

`PS D:\Python_Programming_Zed_Show\Python27_Projects\simple_solver> pip install pyboleto
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A futur
st/development/release-process/#python-2-support
Collecting pyboleto
  Downloading https://files.pythonhosted.org/packages/6f/22/3073b4454e2dba011a95b6a1ee40a8d9fca3f3a3381b0b984b923ea146e2/pyboleto-0.3.1.tar.gz (90kB)
     |################################| 92kB 921kB/s
    ERROR: Command errored out with exit status 1:
     command: 'd:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'d:\\users\\arhitect\\appdata\\local\\temp\\pip-install-ifkxuh\\pyb
ize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-b
         cwd: d:\users\arhitect\appdata\local\temp\pip-install-ifkxuh\pyboleto\
    Complete output (29 lines):
    running egg_info
    creating pip-egg-info\pyboleto.egg-info
    writing requirements to pip-egg-info\pyboleto.egg-info\requires.txt
    writing pip-egg-info\pyboleto.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\pyboleto.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\pyboleto.egg-info\dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\users\arhitect\appdata\local\temp\pip-install-ifkxuh\pyboleto\setup.py", line 78, in <module>
        'sphinx'
      File "d:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "d:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "d:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "d:\users\arhitect\downloads\distribute-0.7.3\distribute-0.7.3\setuptools\command\egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "d:\users\arhitect\downloads\distribute-0.7.3\distribute-0.7.3\pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "d:\users\arhitect\downloads\distribute-0.7.3\distribute-0.7.3\pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "d:\users\arhitect\downloads\distribute-0.7.3\distribute-0.7.3\pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "d:\users\arhitect\downloads\distribute-0.7.3\distribute-0.7.3\pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "d:\users\arhitect\downloads\distribute-0.7.3\distribute-0.7.3\pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
PS D:\Python_Programming_Zed_Show\Python27_Projects\simple_solver> pip install -U setuptools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A futur
st/development/release-process/#python-2-support
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 0.8b2
    Uninstalling setuptools-0.8b2:
      Successfully uninstalled setuptools-0.8b2
Successfully installed setuptools-41.2.0
PS D:\Python_Programming_Zed_Show\Python27_Projects\simple_solver>

`
