### ISSUE TITLE
Push command gives UnicodeDecodeError on iOS strings file

### ISSUE THREAD

**Issue by zhm** [transifex/transifex-client#133]
When running version `0.12.1` and attempting to run:

``` sh
tx push -s
```

I get:

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 164: invalid start byte
```

It's a standard iOS `Localizable.strings` file in UTF-16. Downgrading to `0.10` lets me successfully upload the file.

To install the older version:

``` sh
pip install 'transifex-client>=0.10.0,<0.10.1'`
```

**Comment by zhm** [comment]
Complete traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/txclib/cmdline.py", line 97, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/usr/local/lib/python2.7/site-packages/txclib/utils.py", line 213, in exec_command
    cmd_fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/txclib/commands.py", line 354, in cmd_push
    no_interactive=options.no_interactive
  File "/usr/local/lib/python2.7/site-packages/txclib/project.py", line 623, in push
    self.get_full_path(sfile)
  File "/usr/local/lib/python2.7/site-packages/txclib/project.py", line 851, in do_url_request
    skip_decode=skip_decode
  File "/usr/local/lib/python2.7/site-packages/txclib/utils.py", line 129, in make_request
    fields=fields
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 73, in request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 164: invalid start byte
```

**Comment by kouk** [comment]
Thanks @zhm for the report. Looks like a bug, we'll check it out.

**Comment by nelefth** [comment]
@zhm I would like to inform you that the issue has been resolved.
