### ISSUE TITLE
Transifex API Encoding Error

### ISSUE THREAD

**Issue by abriemme** [transifex/transifex-client#177]
When i push a source file, i have the following error:

```
tx --traceback push -s -r critizr-reports.base
Pushing translations for resource critizr-reports.base:
Pushing source file (report/locale/fr/LC_MESSAGES/django.po)
Traceback (most recent call last):
  File "/Users/Maxime/.virtualenvs/critizr-1.7/lib/python2.7/site-packages/txclib/cmdline.py", line 105, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/Users/Maxime/.virtualenvs/critizr-1.7/lib/python2.7/site-packages/txclib/utils.py", line 246, in exec_command
    cmd_fn(*args, **kwargs)
  File "/Users/Maxime/.virtualenvs/critizr-1.7/lib/python2.7/site-packages/txclib/commands.py", line 351, in cmd_push
    xliff=xliff
  File "/Users/Maxime/.virtualenvs/critizr-1.7/lib/python2.7/site-packages/txclib/project.py", line 711, in push
    params=params,
  File "/Users/Maxime/.virtualenvs/critizr-1.7/lib/python2.7/site-packages/txclib/project.py", line 954, in do_url_request
    skip_decode=skip_decode
  File "/Users/Maxime/.virtualenvs/critizr-1.7/lib/python2.7/site-packages/txclib/utils.py", line 177, in make_request
    raise Exception(data)
Exception: 'ascii' codec can't encode character u'\xe9' in position 25: ordinal not in range(128)
```

Using transifex-client `0.12.4`

**Comment by nelefth** [comment]
@abriemme could you please contact us at support@transifex.com and provide us with the file you are trying to upload to Transifex?
We could take a better look at it and properly assist you.
Thank you in advance.
