### ISSUE TITLE
ImportError: No module named connection

### ISSUE THREAD

**Issue by laoneo** [transifex/transifex-client#200]
I tried to install transifex from master on an Ubuntu 14.04.5. When I want to run `tx --version` it gives me the following error stack:

```
$ tx --version
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 9, in <module>
    load_entry_point('transifex-client==0.12.5', 'console_scripts', 'tx')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/transifex_client-0.12.5-py2.7.egg/txclib/cmdline.py", line 11, in <module>
    from txclib import utils
  File "/usr/local/lib/python2.7/dist-packages/transifex_client-0.12.5-py2.7.egg/txclib/utils.py", line 29, in <module>
    from txclib.exceptions import (
  File "/usr/local/lib/python2.7/dist-packages/transifex_client-0.12.5-py2.7.egg/txclib/exceptions.py", line 7, in <module>
    from urllib3.connection import ConnectionError
ImportError: No module named connection
```
Is there something missing on my installation? Urllib is on 1.7.1:

```
$ dpkg -l | grep urllib
573:ii  python-urllib3                     1.7.1-1ubuntu4                                           all          HTTP library with thread-safe connection pooling for Python
574:ii  python-urllib3-whl                 1.7.1-1ubuntu4                                           all          HTTP library with thread-safe connection pooling
```

**Comment by laoneo** [comment]
Installing with pip worked, is master broken on Python 2.7?

**Comment by rigaspapas** [comment]
Thanks for your feedback @laoneo. Your guess is right. Transifex client requires the `requests` package, which requires `urllib3>=1.21.1,<1.23`. If you have pip `9.0.1` or greater installed, you can run `pip check` to detect version incompatibilities.

In any case, if you want to use the Transifex client from the master branch, we strongly recommend to use a virtual environment.
