### ISSUE TITLE
Problem with upgrading distribute

### ISSUE THREAD

**Issue by kiranandaru** [transifex/transifex-client#205]
Hello! I tried to upgrade my distribute but i keep getting these report

==================================================================
C:\Python27\Scripts>pip install -U distribute
Collecting distribute
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\distribute.egg-info
    writing requirements to pip-egg-info\distribute.egg-info\requires.txt
    writing pip-egg-info\distribute.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\distribute.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\distribute.egg-info\dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\kirana\appdata\local\temp\pip-build-ve0bg8\distribute\setup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "setuptools\command\egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\kirana\appdata\local\temp\pip-build-ve0bg8\distribute\

===============================================================
please help me!

**Comment by nelefth** [comment]
@kiranandaru could you please try `easy_install distribute` and let me know if that fixes the issue?
