### ISSUE TITLE
"No module named configparser" issue when installing version 0.13.10

### ISSUE THREAD

**Issue by alk-jbuisson** [transifex/transifex-client#295]
We use Python 2.7
And since the version 0.13.10 we cannot install anymore transifex-client (we had to rollback to 0.13.9 to make it work).

`14:31:42  Traceback (most recent call last):
14:31:42    File "env/bin/tx", line 11, in <module>
14:31:42      load_entry_point('transifex-client', 'console_scripts', 'tx')()
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
14:31:42      return get_distribution(dist).load_entry_point(group, name)
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
14:31:42      return ep.load()
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
14:31:42      return self.resolve()
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
14:31:42      module = __import__(self.module_name, fromlist=['__name__'], level=0)
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/transifex_client-0.13.10-py2.7.egg/txclib/cmdline.py", line 7, in <module>
14:31:42      from txclib import utils
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/transifex_client-0.13.10-py2.7.egg/txclib/utils.py", line 6, in <module>
14:31:42      import git
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/GitPython-3.1.3-py2.7.egg/git/__init__.py", line 40, in <module>
14:31:42      from git.config import GitConfigParser  # @NoMove @IgnorePep8
14:31:42    File "/home/deploy/workspace/back-translations/env/lib/python2.7/site-packages/GitPython-3.1.3-py2.7.egg/git/config.py", line 28, in <module>
14:31:42      import configparser as cp
14:31:42  ImportError: No module named configparser`

Is it a known problem.
Thanks.
Jerome

**Comment by diegobz** [comment]
It looks like we need to pin `gitpython<3.0.6` as [3.0.5 is the last version to support Python 2](https://github.com/gitpython-developers/GitPython/blob/master/doc/source/changes.rst#306).

@deathbird  ^^
