### ISSUE TITLE
Receiving error from transifex client

### ISSUE THREAD

**Issue by rgbskills** [transifex/transifex-client#322]
Hello, 

I installed transifex-client on macOS 11.4 but i'm receiving the following error:

```
tx pull
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 11, in <module>
    load_entry_point('transifex-client==0.14.2', 'console_scripts', 'tx')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/transifex_client-0.14.2-py2.7.egg/txclib/cmdline.py", line 7, in <module>
    from txclib import utils, web
  File "/Library/Python/2.7/site-packages/transifex_client-0.14.2-py2.7.egg/txclib/utils.py", line 6, in <module>
    import git
  File "/Library/Python/2.7/site-packages/GitPython-3.1.17-py2.7.egg/git/__init__.py", line 21
    def _init_externals() -> None:
                          ^
SyntaxError: invalid syntax
```

**Comment by transifexGithub** [comment]
Hello rgbskills,

Thank you for contacting Transifex support, Basing on the log you sent us It seems that you have compatibility issue, Could you please sent us the output of the following command:
Command: tx --version
0.14.2, py 3.9, arm64
Also could you tell us which version of python are you running

Best Regards

**Comment by rgbskills** [comment]
`tx --version` :
```% tx --version
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 11, in <module>
    load_entry_point('transifex-client==0.14.2', 'console_scripts', 'tx')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/transifex_client-0.14.2-py2.7.egg/txclib/cmdline.py", line 7, in <module>
    from txclib import utils, web
  File "/Library/Python/2.7/site-packages/transifex_client-0.14.2-py2.7.egg/txclib/utils.py", line 6, in <module>
    import git
  File "/Library/Python/2.7/site-packages/GitPython-3.1.17-py2.7.egg/git/__init__.py", line 21
    def _init_externals() -> None:
                          ^
SyntaxError: invalid syntax```
```
And my running python version
python --version
Python 2.7.16
```

**Comment by transifexGithub** [comment]
Thank you!, Could you please share the installation process of TX?

**Comment by rgbskills** [comment]
Yes I installed it wit PIP

```
$ easy_install pip
$ pip install transifex-client
```

**Comment by transifexGithub** [comment]
Hello rgbSkills,

I manage to reproduce your scenario:

> cesar@MacBookCesar ~ % tx --version
> Traceback (most recent call last):
>   File "/usr/local/bin/tx", line 11, in <module>
>     load_entry_point('transifex-client==0.14.2', 'console_scripts', 'tx')()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
>     return ep.load()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
>     return self.resolve()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/Library/Python/2.7/site-packages/transifex_client-0.14.2-py2.7.egg/txclib/cmdline.py", line 7, in <module>
>     from txclib import utils, web
>   File "/Library/Python/2.7/site-packages/transifex_client-0.14.2-py2.7.egg/txclib/utils.py", line 6, in <module>
>     import git
>   File "/Library/Python/2.7/site-packages/GitPython-3.1.14-py2.7.egg/git/__init__.py", line 27
>     raise ImportError("'gitdb' could not be found in your PYTHONPATH") from e

                                                                          ^
SyntaxError: invalid syntax

**The output above is because TX hasn't being install, So let's try installin TX with PIP3 as the example below:**

Command #1
cesar@MacBook-Air-de-Cesar ~ % sudo pip3 install transifex-client

Command#2
cesar@MacBook-Air-de-Cesar ~ % pip3 install --upgrade transifex-client

Command #3
cesar@MacBook-Air-de-Cesar ~ % tx --version
**0.14.2, py 3.9, arm64**

Give it a try and let me know how it goes :)

Best Regards Cesar
