### ISSUE TITLE
Can push source plain text file

### ISSUE THREAD

**Issue by lasconic** [transifex/transifex-client#70]
Hi, I can't push a plain text file. I might miss something or it could be a bug.

I'm using https://pypi.python.org/pypi/transifex-client/0.11.1.beta (same problem with stable version 1.0)

Relevant tx config section

```
[description.txt]
file_filter = description/description_<lang>.txt
source_file = description/description_en.txt
source_lang = en
type = TXT
```

in the root of my project

```
$ ls description/
description_en.txt  description_fr.txt
```

And here is the problem

```
$ tx -d --traceback  push -r description.txt -s
```

Output

```
Path to tx is /Users/username/myproject.
Config file is /Users/username/myproject/.tx/config
.transifexrc file is at /Users/username
.transifexrc file is at /Users/username/myproject
Operating on resources: ['description.txt']
Language mapping is: Flipdict({})
Using host https://www.transifex.com
Pushing translations for resource description.txt:
Resource not found, creating...
Pushing source file (description/description_en.txt)
Resource does not exist.  Creating...
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 94, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/Library/Python/2.7/site-packages/txclib/utils.py", line 182, in exec_command
    cmd_fn(*args,**kwargs)
  File "/Library/Python/2.7/site-packages/txclib/commands.py", line 336, in cmd_push
    no_interactive=options.no_interactive
  File "/Library/Python/2.7/site-packages/txclib/project.py", line 606, in push
    self._create_resource(resource, project_slug, fileinfo, filename)
  File "/Library/Python/2.7/site-packages/txclib/project.py", line 1218, in _create_resource
    r, charset = make_request(method, hostname, url, username, passwd, data)
  File "/Library/Python/2.7/site-packages/txclib/utils.py", line 111, in make_request
    raise HttpNotFound(data)
HttpNotFound: Not Found
```

**Comment by bittner** [comment]
Related to #51. Error handling and reporting could be improved before releasing a non-beta version of `transifex-client`, finally.
