### ISSUE TITLE
Path issues on Windows

### ISSUE THREAD

**Issue by Ede123** [transifex/transifex-client#80]
I just moved my tx.exe (version 0.10) from my project folder to a folder which is contained in the search path (`C:\Windows\System32`) so I can use it from multiple projects at the same time.

However it turns out that this does not work. When running tx.exe (with or without any arguments) the following error is displayed on console:
```
Traceback (most recent call last):
  File "C:\Documents and Settings\mpessas\Application Data\Python\Python27\site-packages\py2exe\boot_common.py", line 92, in <module>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "tx", line 4, in <module>
ImportError: No module named optparse
```
(Note that I'm not `mpessas`)

**Comment by diegobz** [comment]
This should be fixed in the next release. We have migrated to PyInstaller (#101) to generate the tx.exe now.
