### ISSUE TITLE
Pushing a nb_NO translation gives a Unicode encoding python error

### ISSUE THREAD

**Issue by dracos** [transifex/transifex-client#83]
The error is coming from the server (it's returning a 400), though my file contains no `\xe5` character (the only non-ASCII it contains are a couple of smart quotes). Other languages (e.g. it, sv_SE and en) push okay. The .po file is available at https://github.com/mysociety/mapit/blob/master/mapit_no/locale/nb_NO/LC_MESSAGES/django.po and here's the traceback I receive:

```
$ tx --traceback push -f -t -l nb_NO -r mapit.mapit_no
Pushing translations for resource mapit.mapit_no:
Warning: By using --force, the uploaded files will overwrite remote translations, even if they are newer than your uploaded files.
Are you sure you want to continue? [y/N] y
Pushing 'nb_NO' translations (file: mapit_no/locale/nb_NO/LC_MESSAGES/django.po)
Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/mapit-1.7/bin/tx", line 94, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/Users/matthew/.virtualenvs/mapit-1.7/lib/python2.7/site-packages/txclib/utils.py", line 182, in exec_command
    cmd_fn(*args,**kwargs)
  File "/Users/matthew/.virtualenvs/mapit-1.7/lib/python2.7/site-packages/txclib/commands.py", line 336, in cmd_push
    no_interactive=options.no_interactive
  File "/Users/matthew/.virtualenvs/mapit-1.7/lib/python2.7/site-packages/txclib/project.py", line 678, in push
    )], language=remote_lang
  File "/Users/matthew/.virtualenvs/mapit-1.7/lib/python2.7/site-packages/txclib/project.py", line 829, in do_url_request
    return make_request(method, hostname, url, username, passwd, data)
  File "/Users/matthew/.virtualenvs/mapit-1.7/lib/python2.7/site-packages/txclib/utils.py", line 113, in make_request
    raise Exception(data)
Exception: 'ascii' codec can't encode character u'\xe5' in position 87: ordinal not in range(128)
```

**Comment by ffissore** [comment]
I'm having a similar problem when pulling. Is there a workaround?

**Comment by dschuermann** [comment]
Also having this problem. See https://github.com/open-keychain/open-keychain/issues/1128

**Comment by kouk** [comment]
@dracos @ffissore @dschuermann this particular issue is due to a bug in the Transifex API specifically related to Norsk Bookmaal. We are pushing out a fix asap.

**Comment by SofiaMargariti** [comment]
The issue was related to some unicode characters in the language name `Norwegian Bokmål` and it has been fixed.
