### ISSUE TITLE
str/bytes issue when doing `tx push`

### ISSUE THREAD

**Issue by Juanlu001** [transifex/transifex-client#90]
```
$ tx --traceback push -s -t
Pushing translations for resource web-pycones-2015.web:
Pushing source file (pycones/locale/en/LC_MESSAGES/django.po)
Resource does not exist.  Creating...
Traceback (most recent call last):
  File "env/bin/tx", line 94, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "env/lib/python3.4/site-packages/txclib/utils.py", line 182, in exec_command
    cmd_fn(*args,**kwargs)
  File "env/lib/python3.4/site-packages/txclib/commands.py", line 336, in cmd_push
    no_interactive=options.no_interactive
  File "env/lib/python3.4/site-packages/txclib/project.py", line 606, in push
    self._create_resource(resource, project_slug, fileinfo, filename)
  File "env/lib/python3.4/site-packages/txclib/project.py", line 1218, in _create_resource
    r, charset = make_request(method, hostname, url, username, passwd, data)
  File "env/lib/python3.4/site-packages/txclib/utils.py", line 104, in make_request
    r = connection.request(method, url, headers=headers, fields=fields)
  File "env/lib/python3.4/site-packages/txclib/packages/urllib3/request.py", line 79, in request
    **urlopen_kw)
  File "env/lib/python3.4/site-packages/txclib/packages/urllib3/request.py", line 142, in request_encode_body
    **urlopen_kw)
  File "env/lib/python3.4/site-packages/txclib/packages/urllib3/connectionpool.py", line 529, in urlopen
    if assert_same_host and not self.is_same_host(url):
  File "env/lib/python3.4/site-packages/txclib/packages/urllib3/connectionpool.py", line 438, in is_same_host
    if url.startswith('/'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by Juanlu001** [comment]
According to https://github.com/transifex/transifex-client/issues/97#issuecomment-154548918, this can be closed.
